# TASK 1
dataset link : https://raw.githubusercontent.com/TirendazAcademy/PANDAS-TUTORIAL/main/DataSets/vgsalesGlobale.csv
#Exercise
Use the dataset of Game, we have explored earlier and perform following operations.

* Calculate the total global sales for all games in the dataset.
* Find the game with the highest global sales.
* Determine the average sales for each region (NA_Sales, EU_Sales, JP_Sales, Other_Sales).
* Find the top 5 most popular game genres based on global sales.
* Calculate the total sales for each genre in each region and find the most popular genre in North America (NA_Sales).
* Display last 10 rows.
* Determine the top 3 gaming platforms with the highest global sales.
* Calculate the market share (percentage of global sales) for each genre.
* Calculate the correlation coefficient between NA_Sales and EU_Sales. (.corr function)

In [ ]:
import pandas
data = pandas.read_csv('/content/vgsalesGlobale.csv')
total = data['Global_Sales'].sum()
print(total)
NA = data["NA_Sales"].mean()
print(NA)
EU = data["EU_Sales"].mean()
print(EU)
JP = data["JP_Sales"].mean()
print(JP)
Other = data["Other_Sales"].mean()
print(Other)
data['EU_Sales'].corr(data['NA_Sales'])

8920.44
0.26466742981082064
0.14665200626581515
0.077781660441017
0.0480630196409206

0.7677267483702631

In [ ]:
#This is test

In [ ]:
data.tail(10)

,Rank,Name,Platform,Year,Genre,Publisher,NA_Sales,EU_Sales,JP_Sales,Other_Sales,Global_Sales
16588,16591,Mega Brain Boost,DS,2008.0,Puzzle,Majesco Entertainment,0.01,0.00,0.00,0.0,0.01
16589,16592,Chou Ezaru wa Akai Hana: Koi wa Tsuki ni Shiru...,PSV,2016.0,Action,dramatic create,0.00,0.00,0.01,0.0,0.01
16590,16593,Eiyuu Densetsu: Sora no Kiseki Material Collec...,PSP,2007.0,Role-Playing,Falcom Corporation,0.00,0.00,0.01,0.0,0.01
16591,16594,Myst IV: Revelation,PC,2004.0,Adventure,Ubisoft,0.01,0.00,0.00,0.0,0.01
16592,16595,Plushees,DS,2008.0,Simulation,Destineer,0.01,0.00,0.00,0.0,0.01
16593,16596,Woody Woodpecker in Crazy Castle 5,GBA,2002.0,Platform,Kemco,0.01,0.00,0.00,0.0,0.01
16594,16597,Men in Black II: Alien Escape,GC,2003.0,Shooter,Infogrames,0.01,0.00,0.00,0.0,0.01
16595,16598,SCORE International Baja 1000: The Official Game,PS2,2008.0,Racing,Activision,0.00,0.00,0.00,0.0,0.01
16596,16599,Know How 2,DS,2010.0,Puzzle,7G//AMES,0.00,0.01,0.00,0.0,0.01
16597,16600,Spirits & Spells,GBA,2003.0,Platform,Wanadoo,0.01,0.00,0.00,0.0,0.01

In [ ]:
data.groupby('Genre').sum()['Global_Sales'].nlargest(n=5)

Genre
Action          1751.18
Sports          1330.93
Shooter         1037.37
Role-Playing     927.37
Platform         831.37
Name: Global_Sales, dtype: float64

In [ ]:
data.groupby('Platform').sum()['Global_Sales'].nlargest(n=3)

Platform
PS2     1255.64
X360     979.96
PS3      957.84
Name: Global_Sales, dtype: float64

In [ ]:
data.groupby('Genre').sum()['Global_Sales']/data['Global_Sales'].sum()*100

Genre
Action          19.631094
Adventure        2.679688
Fighting         5.032375
Misc             9.079821
Platform         9.319832
Puzzle           2.745941
Racing           8.206322
Role-Playing    10.396012
Shooter         11.629135
Simulation       4.396644
Sports          14.920004
Strategy         1.963132
Name: Global_Sales, dtype: float64

In [73]:
data.groupby('Genre').sum()[['NA_Sales','EU_Sales','JP_Sales','Other_Sales']]

              NA_Sales  EU_Sales  JP_Sales  Other_Sales
Genre
Action          877.83    525.00    159.95       187.38
Adventure       105.80     64.13     52.07        16.81
Fighting        223.59    101.32     87.35        36.68
Misc            410.24    215.98    107.76        75.32
Platform        447.05    201.63    130.77        51.59
Puzzle          123.78     50.78     57.31        12.55
Racing          359.42    238.39     56.69        77.27
Role-Playing    327.28    188.06    352.31        59.61
Shooter         582.60    313.27     38.28       102.69
Simulation      183.31    113.38     63.70        31.52
Sports          683.35    376.85    135.37       134.97
Strategy         68.70     45.34     49.46        11.36

In [75]:
data.groupby('Genre').sum()['NA_Sales'].nlargest(n=1)

Genre
Action    877.83
Name: NA_Sales, dtype: float64

## Task 2 English-Spanish Dictionary
You are creating a basic English-Spanish dictionary that allows users to look up English words and find their Spanish translations.


### Tasks
* Create a dictionary where English words are keys and their Spanish translations are values.
* Ask the user to input an English word.
* Check if the word exists in the dictionary.
* If the word exists, print its Spanish translation.
* If the word does not exist, inform the user that the translation is not available.
* Implement a loop that allows the user to keep looking up words until they choose to exit.

In [ ]:
dictionary= {
  "water": "aqua",
  "thanks": "gracias",
  "day": "dia"
}
stop=0
while stop!='1':
  engword=input("Please enter an english word: ")
  if engword in dictionary:
    print(dictionary[engword])
  else:
    print("The word is incorrect or could not be found in the dictonary")
  stop=input("Do you want to stop, press 1 for yes and 0 for no")
  if stop=='1':
    break

Please enter an english word: abcd
The word is incorrect or could not be found in the dictonary
Do you want to stop, press 1 for yes and 0 for no1


## Task 3 Email Classification
Develope a tool which will classify an email.

### Tasks:
* Create a function classify_emails that takes a list of emails as an argument.
* Inside the function, categorize emails into "Important," "Promotions," and "Spam" based on keywords and content analysis.
* Loop through the emails and identify keywords to determine their category.
* If an email contains keywords indicating importance, assign it as "Important."
* If an email contains keywords related to promotions or deals, assign it as "Promotions."
* If an email is suspected to be spam based on certain keywords or patterns, assign it as "Spam."
* Return three lists of emails for each category.
* Print the lists.

In [69]:
def emailclassifier(emails):
  imp=[]
  spam=[]
  promo=[]
  for x in emails:
    if "important" in x or "urgent" in x or "quick" in x:
      imp.append(x)
    elif "discount" in x or "buy" in x or "advertisement" in x or "deal" in x:
      promo.append(x)
    elif "click" in x or "free" in x or "hurry" in x:
      spam.append(x)
  return imp,promo,spam

emails=["hello sir important meeting today please be on time","discount on any purchase from our store starting today","click on this link to get a free laptop"]
imp,promo,spam=emailclassifier(emails)
print(imp)
print(promo)
print(spam)

['hello sir important meeting today please be on time']
['discount on any purchase from our store starting today']
['click on this link to get a free laptop']

## Task 4 Online Store Shopping Cart
Write a Python program to simulate the online store's shopping cart system. The program should use a while loop to provide an interactive shopping experience.


### Tasks:
* Initialize an empty list called shopping_cart to store items.
* Display a welcome message and available products.
* Loop should be iterating over AI Response Simulator and Investment decision and keep asking for user input.
* Prompt the user to enter the number corresponding to the product they want to add to the cart.
* Check if the user entered 'q'. If so, break the loop.
* Convert the choice to an integer and validate it within the valid range (1 to 3).
* Based on the user's choice, add the selected product to the shopping_cart list.
* Display a confirmation message indicating the added product.
* Continue the loop to allow the user to add more products or proceed to checkout.
* After the loop ends, display the contents of the shopping cart.
* Display a goodbye message.
* End the program.

In [71]:
shopping_cart=[]
validlist=[1,2,3]
print("Welcome customer")
cont='1'
while cont!='q':
  productnum=input("Enter the number of the product you want to buy (or press q to exit)")
  if productnum=='q':
    cont='q'
    break
  productnum=int(productnum)
  if productnum not in validlist:
    print("Invalid input")
    break
  if productnum==1:
    shopping_cart.append("chocolate")
  elif productnum==2:
    shopping_cart.append("milk")
  elif productnum==3:
    shopping_cart.append("chips")

print("The shpping cart items are: ")
print(shopping_cart)
print("Goodbye")

Welcome customer
Enter the number of the product you want to buy (or press q to exit)4
Invalid input
The shpping cart items are:
[]
Goodbye

## Task 5
* Create two NumPy arrays of the same shape and perform element-wise addition on them.
* Calculate the element-wise product of two NumPy arrays.

In [ ]:
import numpy as np
array1 = np.array([1, 2, 3, 4])
array2 = np.array([5,6,7,8])
sum = np.add(array1, array2)
print(sum)
product = np.multiply(array1, array2)
print(product)

[ 6  8 10 12]
[ 5 12 21 32]

## Task 6
* Reshape a 1D NumPy array into a 2D array with dimensions (3, 4).

* Concatenate two NumPy arrays horizontally and vertically.

In [67]:
import numpy as np
array = np.array([1, 2, 3, 4,5,6,7,8,9,10,11,12])
array1 = array.reshape(3, 4)
print (array1)
array2 = np.array([4, 5, 6,7,8,9,10,11,12,13,14,15])
array2 = array.reshape(3, 4)
hori = np.concatenate((array1, array2), axis=0)
vert = np.concatenate((array1, array2), axis=1)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]

## Task 7
* Reverse A List In Python Using Slicing

In [ ]:
straight=[4,8,12,16]
size=len(straight)
reversed=straight[::-1]
print(reversed)

[16, 12, 8, 4]

# TASK 8
You need to download the GitHub Desktop software, push your lab task to your GitHub account, and share the link on GCR as a submission.